-----------------------------------------------------------
-- Szinkronfeliratok
-----------------------------------------------------------
-- Keszitette: The Sweet Little 16-bit (tsl16b@freemail.hu)
-----------------------------------------------------------
-- forgottenspiral
-- v0.0
-----------------------------------------------------------

--id														= texture
tips_icons =
{
	bandit                        = "ui_npc_small_bandit_1",
	csky                          = "ui_npc_small_nebo_1",
	dolg                          = "ui_npc_small_dolg_1",
	ecolog                        = "ui_iconsNpc_ecolog",
	freedom                       = "ui_npc_small_freedom_1",
	killer                        = "ui_npc_small_merc_2",
	army                          = "ui_npc_small_soldier_2",
	monolith                      = "ui_npc_small_monolith_1",
	stalker                       = "ui_npc_small_neutral_1",
	trader                        = "ui_iconsNpc_trader",
	zombied                       = "ui_npc_small_zombied_1",
	renegade                      = "ui_npc_small_bandit_1",

	mar_csky_commander_name       = "ui_npc_small_nebo_2_face_1",
	mar_csky_scientist_name       = "ui_npc_small_nebo_2_face_2",
	mar_csky_tech_name            = "ui_npc_small_nebo_2_face_3",
	mar_csky_barman               = "ui_npc_small_nebo_2_face_4",
	escape_trader_name            = "ui_npc_small_trader_1",
	esc_leader_stalkerbase_name   = "ui_npc_small_neutral_2_face_2",
	esc_driver_name               = "ui_npc_small_soldier_1",
	esc_zak_stalkerbase_name      = "ui_npc_small_soldier_2_face_1",
	gar_bandit_leader_name        = "ui_npc_small_bandit_3_face_1",
	gar_bandit_barman_name        = "ui_npc_small_bandit_3_face_2",
	gar_digger_quester_name       = "ui_npc_small_neutral_2_face_1",
	agr_duty_base_commander_name  = "ui_npc_small_dolg_2_face_1",
	agr_weaponmaster_name         = "ui_npc_small_dolg_2_mask",
	agr_barman_name               = "ui_npc_u_dolg_2_face_2",
	val_freedom_leader_name       = "ui_npc_small_freedom_2_face_2",
	val_freedom_trader_name       = "ui_npc_small_freedom_2_mask",
	red_forester_name             = "ui_npc_small_lesnik_1",
	yan_st_sakharov_name          = "ui_npc_small_ucheniy_1",

	-- SRP additions:

	val_freedom_comendant_name    = "ui_npc_small_freedom_3",
	agr_holeman_name              = "ui_npc_small_dolg_2_mask",
	sim_strelok_name              = "ui_npc_small_neutral_2",
	agr_stalker_base_leader_name  = "ui_npc_small_neutral_2_mask",
	esc_wolf_name                 = "ui_npc_small_neutral_2",
	gar_digger_traitor_name       = "ui_npc_small_neutral_1",
	gar_bandit_minigame_name      = "ui_npc_small_bandit_1",
	gar_digger_messenger_man_name = "ui_npc_small_neutral_1",
	mar_csky_barman_name          = "ui_npc_small_nebo_2_face_4",
	mar_csky_guide_name           = "ui_npc_small_nebo_1",
	mil_kostiuk_name              = "ui_npc_small_freedom_4",
	mil_hog_name                  = "ui_npc_small_merc_4",
	red_ally_leshiy_name          = "ui_npc_small_neutral_2_mask",
	yan_st_levsha_name            = "ui_npc_small_neutral_2_mask",
	yan_levshas_crew              = "ui_npc_small_neutral_2",

	-- Subs additions:

	gar_bandit_robbery						= "ui_npc_small_bandit_3",
	temporal_icon									= "ui_npc_small_zombied_4",
}

--id																											=	{showtime}
mob_snds =
{
	-- Sid
	characters_voice_scenario_escape_esc_trader_greet_first	= {3.3},
	characters_voice_scenario_escape_esc_trader_greet_habar	= {4.2},
	characters_voice_scenario_escape_esc_trader_habar_greet_1	= {2.9},
	characters_voice_scenario_escape_esc_trader_habar_greet_2	= {1.4},
	characters_voice_scenario_escape_esc_trader_habar_greet_3	= {2},
	characters_voice_scenario_escape_esc_trader_greet_1	= {1.5},
	characters_voice_scenario_escape_esc_trader_greet_2	= {1.2},
	characters_voice_scenario_escape_esc_trader_greet_3	= {2},
	characters_voice_scenario_escape_esc_trader_greet_4	= {1.3},
	characters_voice_scenario_escape_esc_trader_bye_give_habar	= {2.9},
	characters_voice_scenario_escape_esc_trader_bye_habar_1	= {2.2},
	characters_voice_scenario_escape_esc_trader_bye_habar_2	= {2.1},
	characters_voice_scenario_escape_esc_trader_bye_habar_3	= {2.5},
	characters_voice_scenario_escape_esc_trader_bye_1	= {0.9},
	characters_voice_scenario_escape_esc_trader_bye_2	= {2.7},
	characters_voice_scenario_escape_esc_trader_bye_3	= {1.4},
	characters_voice_scenario_escape_esc_trader_wait_1	= {2.2},
	characters_voice_scenario_escape_esc_trader_wait_2	= {2.7},
	characters_voice_scenario_escape_esc_trader_wait_3	= {3.8},
	characters_voice_scenario_escape_esc_trader_wait_4	= {2.2},
	-- Forester
	characters_voice_scenario_red_forest_red_forester_greet_1	= {3.1},
	characters_voice_scenario_red_forest_red_forester_meet_hello_0	= {3.4},
	characters_voice_scenario_red_forest_red_forester_meet_hello_1	= {2.6},
	characters_voice_scenario_red_forest_red_forester_meet_hello_2	= {3.1},
	characters_voice_scenario_red_forest_red_forester_hello_bye_0	= {2.1},
	characters_voice_scenario_red_forest_red_forester_hello_bye_1	= {1.9},
	characters_voice_scenario_red_forest_red_forester_hello_bye_2	= {1.8},
}

--id																														=	{showtime}
npc_snds =
{
	-- CS
	characters_voice_scenario_marsh_mar_csky_leader_meet_greet_1	= {1.8},
	characters_voice_scenario_marsh_mar_csky_leader_meet_greet_2	= {2.5},
	characters_voice_scenario_marsh_mar_csky_leader_meet_greet_3	= {2},
	characters_voice_scenario_marsh_mar_csky_leader_meet_greet_4	= {2.9},
	characters_voice_scenario_marsh_mar_csky_leader_meet_bye_1	= {3.3},
	characters_voice_scenario_marsh_mar_csky_leader_meet_bye_2	= {0.7},
	characters_voice_scenario_marsh_mar_csky_leader_meet_bye_3	= {2.6},
	characters_voice_scenario_marsh_mar_csky_leader_meet_bye_4	= {2.3},
	characters_voice_scenario_marsh_mar_csky_doctor_meet_greet_1	= {0.9},
	characters_voice_scenario_marsh_mar_csky_doctor_meet_greet_2	= {5.5},
	characters_voice_scenario_marsh_mar_csky_doctor_meet_greet_3	= {1.2},
	characters_voice_scenario_marsh_mar_csky_doctor_meet_bye_1	= {2.3},
	characters_voice_scenario_marsh_mar_csky_doctor_meet_bye_2	= {3.5},
	characters_voice_scenario_marsh_mar_csky_doctor_meet_bye_3	= {3.5},
	characters_voice_scenario_marsh_mar_csky_barman_meet_greet_1	= {2},
	characters_voice_scenario_marsh_mar_csky_barman_meet_greet_2	= {2.1},
	characters_voice_scenario_marsh_mar_csky_barman_meet_greet_3	= {4.7},
	characters_voice_scenario_marsh_mar_csky_barman_meet_bye_1	= {2.2},
	characters_voice_scenario_marsh_mar_csky_barman_meet_bye_2	= {3.4},
	characters_voice_scenario_marsh_mar_csky_barman_meet_bye_3	= {3.6},
	characters_voice_scenario_marsh_mar_csky_trader_meet_greet_1	= {1.9},
	characters_voice_scenario_marsh_mar_csky_trader_meet_greet_2	= {0.6},
	characters_voice_scenario_marsh_mar_csky_trader_meet_greet_3	= {2.3},
	characters_voice_scenario_marsh_mar_csky_trader_meet_bye_1	= {0.8},
	characters_voice_scenario_marsh_mar_csky_trader_meet_bye_2	= {0.9},
	characters_voice_scenario_marsh_mar_csky_trader_meet_bye_3	= {2.4},
	characters_voice_scenario_marsh_mar_csky_tech_meet_greet_1	= {1.2},
	characters_voice_scenario_marsh_mar_csky_tech_meet_greet_2	= {6},
	characters_voice_scenario_marsh_mar_csky_tech_meet_greet_3	= {3.7},
	characters_voice_scenario_marsh_mar_csky_tech_meet_bye_1	= {4},
	characters_voice_scenario_marsh_mar_csky_tech_meet_bye_2	= {2.7},
	characters_voice_scenario_marsh_mar_csky_tech_meet_bye_3	= {1.1},
	--- Stalker
	characters_voice_scenario_escape_esc_stalker_trader_meet_1	= {1.3},
	characters_voice_scenario_escape_esc_stalker_trader_meet_2	= {1.6},
	characters_voice_scenario_escape_esc_stalker_trader_meet_3	= {1.5},
	characters_voice_scenario_escape_esc_stalker_trader_meet_bye_1	= {1.9},
	characters_voice_scenario_escape_esc_stalker_trader_meet_bye_2	= {2.2},
	characters_voice_scenario_escape_esc_stalker_trader_meet_bye_3	= {2.4},
	characters_voice_scenario_escape_esc_stalker_mechanic_meet_1	= {1.6},
	characters_voice_scenario_escape_esc_stalker_mechanic_meet_2	= {2},
	characters_voice_scenario_escape_esc_stalker_mechanic_meet_3	= {1.1},
	characters_voice_scenario_escape_esc_stalker_mechanic_meet_bye_1	= {1.7},
	characters_voice_scenario_escape_esc_stalker_mechanic_meet_bye_2	= {2.1},
	characters_voice_scenario_escape_esc_stalker_mechanic_meet_bye_3	= {4.3},
	characters_voice_scenario_escape_esc_military_prisoner_meet_1	= {2.2},
	characters_voice_scenario_escape_esc_military_prisoner_meet_2	= {3.6},
	characters_voice_scenario_escape_esc_military_prisoner_meet_3	= {3.5},
	characters_voice_scenario_escape_esc_military_prisoner_meet_bye_1	= {2.6},
	characters_voice_scenario_escape_esc_military_prisoner_meet_bye_2	= {1.7},
	characters_voice_scenario_escape_esc_military_prisoner_meet_bye_3	= {5.1},
	--- Bandits
	characters_voice_scenario_garbage_gar_bandit_leader_meet_greet_a_1	= {3.1},
	characters_voice_scenario_garbage_gar_bandit_leader_meet_greet_a_2	= {2.4},
	characters_voice_scenario_garbage_gar_bandit_leader_meet_greet_b_1	= {3.1},
	characters_voice_scenario_garbage_gar_bandit_leader_meet_bye_a_1	= {2},
	characters_voice_scenario_garbage_gar_bandit_leader_meet_bye_a_2	= {2.4},
	characters_voice_scenario_garbage_gar_bandit_leader_meet_bye_b_1	= {2.4},
	characters_voice_scenario_garbage_gar_bandit_leader_meet_bye_b_2	= {3},
	characters_voice_scenario_garbage_gar_bandit_tech_meet_greet_1	= {3.9},
	characters_voice_scenario_garbage_gar_bandit_tech_meet_greet_2	= {2.1},
	characters_voice_scenario_garbage_gar_bandit_tech_meet_greet_3	= {2.8},
	characters_voice_scenario_garbage_gar_bandit_tech_meet_bye_1	= {3.6},
	characters_voice_scenario_garbage_gar_bandit_tech_meet_bye_2	= {2.2},
	characters_voice_scenario_garbage_gar_bandit_tech_meet_bye_3	= {2.8},
	characters_voice_scenario_garbage_gar_bandit_trader_meet_greet_1	= {1},
	characters_voice_scenario_garbage_gar_bandit_trader_meet_greet_2	= {2},
	characters_voice_scenario_garbage_gar_bandit_trader_meet_greet_3	= {2},
	characters_voice_scenario_garbage_gar_bandit_trader_meet_bye_1	= {1.8},
	characters_voice_scenario_garbage_gar_bandit_trader_meet_bye_2	= {2.2},
	characters_voice_scenario_garbage_gar_bandit_trader_meet_bye_3	= {1.6},
	characters_voice_scenario_garbage_gar_bandit_barman_meet_greet_1	= {1.7},
	characters_voice_scenario_garbage_gar_bandit_barman_meet_greet_2	= {5.2},
	characters_voice_scenario_garbage_gar_bandit_barman_meet_greet_3	= {2.7},
	characters_voice_scenario_garbage_gar_bandit_barman_meet_bye_1	= {3},
	characters_voice_scenario_garbage_gar_bandit_barman_meet_bye_2	= {4},
	characters_voice_scenario_garbage_gar_bandit_barman_meet_bye_3	= {3.3},
	characters_voice_scenario_garbage_gar_bandit_bookmaker_meet_greet_1	= {2.5},
	characters_voice_scenario_garbage_gar_bandit_bookmaker_meet_greet_2	= {3.7},
	characters_voice_scenario_garbage_gar_bandit_bookmaker_meet_greet_3	= {2.7},
	characters_voice_scenario_garbage_gar_bandit_bookmaker_meet_bye_1	= {2.8},
	characters_voice_scenario_garbage_gar_bandit_bookmaker_meet_bye_2	= {2.8},
	characters_voice_scenario_garbage_gar_bandit_bookmaker_meet_bye_3	= {3.9},
	characters_voice_scenario_garbage_gar_digger_leader_meet_greet_1	= {0.9},
	characters_voice_scenario_garbage_gar_digger_leader_meet_greet_2	= {0.7},
	characters_voice_scenario_garbage_gar_digger_leader_meet_greet_3	= {1.8},
	characters_voice_scenario_garbage_gar_digger_leader_meet_bye_1	= {1.3},
	characters_voice_scenario_garbage_gar_digger_leader_meet_bye_2	= {0.9},
	characters_voice_scenario_garbage_gar_digger_leader_meet_bye_3	= {1},
	-- Freedom
	characters_voice_scenario_darkvalley_val_freedom_leader_meet_1	= {1.1},
	characters_voice_scenario_darkvalley_val_freedom_leader_meet_2	= {2.1},
	characters_voice_scenario_darkvalley_val_freedom_leader_meet_3	= {1.6},
	characters_voice_scenario_darkvalley_val_freedom_leader_meet_bye_1	= {2.6},
	characters_voice_scenario_darkvalley_val_freedom_leader_meet_bye_2	= {2.9},
	characters_voice_scenario_darkvalley_val_freedom_leader_meet_bye_3	= {2.2},
	characters_voice_scenario_darkvalley_val_freedom_comendant_meet_1	= {2.8},
	characters_voice_scenario_darkvalley_val_freedom_comendant_meet_2	= {3.2},
	characters_voice_scenario_darkvalley_val_freedom_comendant_meet_3	= {2.9},
	characters_voice_scenario_darkvalley_val_freedom_comendant_meet_bye_1	= {1.9},
	characters_voice_scenario_darkvalley_val_freedom_comendant_meet_bye_2	= {3.3},
	characters_voice_scenario_darkvalley_val_freedom_comendant_meet_bye_3	= {4.3},
	characters_voice_scenario_darkvalley_val_freedom_barmen_meet_1	= {2.2},
	characters_voice_scenario_darkvalley_val_freedom_barmen_meet_2	= {4.2},
	characters_voice_scenario_darkvalley_val_freedom_barmen_meet_3	= {5.6},
	characters_voice_scenario_darkvalley_val_freedom_barmen_meet_bye_1	= {7},
	characters_voice_scenario_darkvalley_val_freedom_barmen_meet_bye_2	= {4},
	characters_voice_scenario_darkvalley_val_freedom_barmen_meet_bye_3	= {4.3},
	characters_voice_scenario_darkvalley_val_freedom_trader_meet_1	= {2.3},
	characters_voice_scenario_darkvalley_val_freedom_trader_meet_2	= {3.4},
	characters_voice_scenario_darkvalley_val_freedom_trader_meet_3	= {2.9},
	characters_voice_scenario_darkvalley_val_freedom_trader_meet_bye_1	= {2.5},
	characters_voice_scenario_darkvalley_val_freedom_trader_meet_bye_2	= {4.2},
	characters_voice_scenario_darkvalley_val_freedom_trader_meet_bye_3	= {2.9},
	characters_voice_scenario_darkvalley_val_freedom_fixer_meet_1	= {1.9},
	characters_voice_scenario_darkvalley_val_freedom_fixer_meet_2	= {1.4},
	characters_voice_scenario_darkvalley_val_freedom_fixer_meet_3	= {1.5},
	characters_voice_scenario_darkvalley_val_freedom_fixer_meet_bye_1	= {1},
	characters_voice_scenario_darkvalley_val_freedom_fixer_meet_bye_2	= {1.7},
	characters_voice_scenario_darkvalley_val_freedom_fixer_meet_bye_3	= {5.5},
	-- Duty
	-- characters_voice_scenario_marsh_bloodsucker_fear_1	= {5},
	-- characters_voice_scenario_marsh_bloodsucker_fear_2	= {5},
	-- characters_voice_scenario_marsh_bloodsucker_fear_3	= {5},
	-- characters_voice_scenario_marsh_bloodsucker_fear_fire_1	= {5},
	-- characters_voice_scenario_marsh_bloodsucker_fear_fire_2	= {5},
	-- characters_voice_scenario_marsh_bloodsucker_squad_fear_1	= {5},
	-- characters_voice_scenario_marsh_bloodsucker_squad_fear_2	= {5},
	-- characters_voice_scenario_marsh_bloodsucker_squad_fear_3	= {5},
	characters_voice_scenario_agroprom_agr_duty_leader_meet_1	= {1.1},
	characters_voice_scenario_agroprom_agr_duty_leader_meet_2	= {3.2},
	characters_voice_scenario_agroprom_agr_duty_leader_meet_3	= {1.8},
	characters_voice_scenario_agroprom_agr_duty_leader_meet_bye_1	= {0.9},
	characters_voice_scenario_agroprom_agr_duty_leader_meet_bye_2	= {0.8},
	characters_voice_scenario_agroprom_agr_duty_leader_meet_bye_3	= {0.7},
	characters_voice_scenario_agroprom_agr_duty_barman_meet_1	= {4.5},
	characters_voice_scenario_agroprom_agr_duty_barman_meet_2	= {2.5},
	characters_voice_scenario_agroprom_agr_duty_barman_meet_3	= {1.8},
	characters_voice_scenario_agroprom_agr_duty_barman_meet_bye_1	= {2.5},
	characters_voice_scenario_agroprom_agr_duty_barman_meet_bye_2	= {3.2},
	characters_voice_scenario_agroprom_agr_duty_barman_meet_bye_3	= {3.4},
	characters_voice_scenario_agroprom_agr_duty_trader_meet_1	= {3.1},
	characters_voice_scenario_agroprom_agr_duty_trader_meet_2	= {1.3},
	characters_voice_scenario_agroprom_agr_duty_trader_meet_3	= {5.4},
	characters_voice_scenario_agroprom_agr_duty_trader_meet_bye_1	= {0.8},
	characters_voice_scenario_agroprom_agr_duty_trader_meet_bye_2	= {2.1},
	characters_voice_scenario_agroprom_agr_duty_trader_meet_bye_3	= {2.4},
	characters_voice_scenario_agroprom_agr_duty_weaponmaster_meet_1	= {1.1},
	characters_voice_scenario_agroprom_agr_duty_weaponmaster_meet_2	= {1.8},
	characters_voice_scenario_agroprom_agr_duty_weaponmaster_meet_3	= {7.3},
	characters_voice_scenario_agroprom_agr_duty_weaponmaster_meet_bye_1	= {3},
	characters_voice_scenario_agroprom_agr_duty_weaponmaster_meet_bye_2	= {3.3},
	characters_voice_scenario_agroprom_agr_duty_weaponmaster_meet_bye_3	= {2.3},
	characters_voice_scenario_agroprom_agr_duty_zooman_meet_1	= {2.6},
	characters_voice_scenario_agroprom_agr_duty_zooman_meet_2	= {4.1},
	characters_voice_scenario_agroprom_agr_duty_zooman_meet_3	= {4},
	characters_voice_scenario_agroprom_agr_duty_zooman_meet_bye_1	= {2.9},
	characters_voice_scenario_agroprom_agr_duty_zooman_meet_bye_2	= {4.1},
	characters_voice_scenario_agroprom_agr_duty_zooman_meet_bye_3	= {2.6},
	-- Scientist
	characters_voice_scenario_yantar_yan_sakharov_meet_1	= {1.3},
	characters_voice_scenario_yantar_yan_sakharov_meet_2	= {2.3},
	characters_voice_scenario_yantar_yan_sakharov_meet_3	= {1.5},
	characters_voice_scenario_yantar_yan_sakharov_meet_bye_1	= {0.9},
	characters_voice_scenario_yantar_yan_sakharov_meet_bye_2	= {1.3},
	characters_voice_scenario_yantar_yan_sakharov_meet_bye_3	= {1.7},
}

--id																										=	{showtime, sender}
actor_snds =
{
	-- original prefix: scenario_...
	characters_voice_scenario_agroprom_agr_blokpost_shout_1	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_base_commander_reward_pda	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_base_leader_sergant_1	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_base_leader_sergant_2	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_base_leader_sergant_3	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_base_leader_sergant_4	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_base_leader_sergant_5	=	{5, "temporal_icon"},
	-- characters_voice_scenario_generator_uno_commander_story_1	=	{5, "temporal_icon"},
	-- characters_voice_scenario_generator_uno_commander_story_1b	=	{5, "temporal_icon"},
	-- characters_voice_scenario_generator_uno_target_reached	=	{5, "temporal_icon"},
	-- characters_voice_scenario_generator_uno_target_reply	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_request_help	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_about_hall	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_wait_pda	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_go_pda	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_suicide	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_well	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_badly_pda_1	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_badly_pda_2	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_badly_pda_3	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_danger	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_hospital_kill_actor	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_hospital_kill_actor_intercept	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_kill_sniper	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_kill_sniper_now_1	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_kill_sniper_now_2	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_start_raid	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_cover_us	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_gunner_killed	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_thanks_actor	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_helicopter_see_enemy	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_helicopter_kill_order	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_helicopter_start_attack	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_enemy_see_helicopter	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_helicopter_killed	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_hold_on	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_arrived	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_start_block	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_block_1	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_block_2	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_kill_dot	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_victory	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_clear_sky_victory_reply	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_hospital_z3_csky_com_apply	=	{5, "temporal_icon"},
	characters_voice_scenario_hospital_hospital_z3_csky_com_order	=	{5, "temporal_icon"},
	-- original prefix: characters_voice_scenario_...
	characters_voice_scenario_agroprom_agr_dolg_expansion_0_up	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_dolg_expansion_1_up	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_dolg_expansion_1_down	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_dolg_expansion_2_up	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_dolg_expansion_2_down	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_dolg_expansion_3_up	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_dolg_expansion_3_down	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_dolg_expansion_4_up	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_dolg_expansion_4_down	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_agr_dolg_expansion_5_down	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_underground_agru_leader_clear_sky_pda	=	{5, "temporal_icon"},
	characters_voice_scenario_agroprom_underground_agru_leader_dolg_pda	=	{5, "temporal_icon"},
	-- characters_voice_scenario_agroprom_underground_agru_radio	=	{5, "sim_strelok_name"}, -- Strelok's PDA Recording
	characters_voice_scenario_darkvalley_val_freedom_blockpost_enter	=	{11, "val_freedom_comendant_name"},
	characters_voice_scenario_darkvalley_val_freedom_blockpost_robbery_return	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_base_enter	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_comendant_come_back	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_leader_help	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_leader_come_back	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_leader_pda_come_back	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_killer_trep	=	{15, "killer"},
	characters_voice_scenario_darkvalley_val_freedom_attack_help	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_antenna_control	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_antenna_finish	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_antenna_good	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_antenna_poterya_controlya	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_zavod_help	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_zavod_task	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_ambush_in_yard	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_zavod_task_sniper_dead	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_ambush_end	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_quest_finish	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_0_up	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_1_up	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_1_down	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_2_up	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_2_down	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_3_up	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_3_down	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_4_up	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_4_down	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_freedom_expansion_5_down	=	{5, "temporal_icon"},
	characters_voice_scenario_darkvalley_val_leader_join_freedom	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_trader_spot	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_trader_call	=	{5, "temporal_icon"},
	characters_voice_scenario_trader_trader_script1a_3	=	{5, "temporal_icon"},
	-- characters_voice_scenario_escape_esc_mill_complete_reply	=	{5, "temporal_icon"},
	-- characters_voice_scenario_escape_esc_trader_habar_request	=	{5, "temporal_icon"},
	-- characters_voice_scenario_escape_esc_dead_military_pda_request	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_patrol_help_1	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_patrol_help_2	=	{5, "temporal_icon"},
	-- characters_voice_scenario_escape_esc_trader_start_pda	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_trader_greet_1	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_trader_greet_2	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_trader_greet_3	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_trader_greet_4	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_1_1	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_1_2	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_2_1	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_2_2	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_2_3	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_2_4	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_3_1	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_3_2	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_3_3	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_3_4	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_4_1	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_4_2	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_assemble_4_3	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_trader_bye_give_habar	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_expansion_0_up	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_expansion_1_up	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_expansion_1_down	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_expansion_2_up	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_expansion_2_down	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_expansion_4_up	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_expansion_3_down	=	{5, "temporal_icon"},
	characters_voice_scenario_escape_esc_stalker_expansion_5_down	=	{5, "temporal_icon"},
	-- characters_voice_scenario_escape_esc_can_join_stalker_1	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_dead_digger_leader_rec	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_digger_messenger_pda_rec	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_stalker_group_talk	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_fang_pda_rec	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_find_fang_pda	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_csky_leader_goto_agroprom	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_digger_quester_looked_at_dead_camp	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_digger_leader_looked_at_dead_camp_a	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_digger_leader_looked_at_dead_camp_b	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_leader_destroy_flea_market_done	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_digger_quester_creature_attack	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_digger_quester_creature_gone	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_digger_quester_creature_killed	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_conc_camp_go_away	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_leader_join_message	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_expansion_0_up	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_expansion_1_up	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_expansion_1_down	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_expansion_2_up	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_expansion_2_down	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_expansion_4_up	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_expansion_3_down	=	{5, "temporal_icon"},
	characters_voice_scenario_garbage_gar_bandit_expansion_5_down	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_storm_troop_leader_clear_street	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_storm_troop_leader_to_actor1	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_stalker_spich	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_reconnaissance_squad_alert	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_reconnaissance_squad_clear	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_reconnaissance_squad_to_actor	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_enter_squad_attention	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_enter_squad_see_target	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_enter_squad_check	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_reconnaissance_squad_electricity_off_pda	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_leader_next_task	=	{5, "temporal_icon"},
	characters_voice_scenario_limansk_lim_cs_storm_troop_leader_stay	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_tower_captured	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_boars_killed	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_plant_captured	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_tower_captured_to_actor	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_defend_tower	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_capture_plant	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_helicopter_scan	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_helicopter_base_attack	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_helicopter_attack_confirm	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_helicopter_base_moveout	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_helicopter_moveout_confirm	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_helicopter_lost	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_leader_to_barman_0	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_leader_starting_surge_0	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_commander_tutorial_anomalies	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_commander_tutorial_artefacts	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_forpost_sos	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_expansion_0_up	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_expansion_1_up	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_expansion_1_down	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_expansion_2_up	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_expansion_2_down	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_expansion_3_down	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_pathfinder_go_out_1	=	{5, "temporal_icon"},
	characters_voice_scenario_marsh_mar_csky_arrive_on_open_marsh_1	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_bs_dead	= {3.9, "mil_hog_name"},
	characters_voice_scenario_military_mil_hog_to_actor	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_hog_to_freedom_1	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_hog_to_freedom_3	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_hog_to_freedom_5	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_hog_to_freedom_7	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_rnd_radio_1	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_rnd_radio_2	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_rnd_radio_3	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_rnd_radio_4	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_rnd_radio_5	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_rnd_radio_6	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_rnd_radio_7	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_rnd_radio_8	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_stalker_radio_1	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_meet_4n_com_task	=	{5, "temporal_icon"},
	characters_voice_scenario_military_mil_hires_in_bubble_thanks_1	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_actor_fail	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_actor_flee	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_actor_hail	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_assault_start	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_bandits_1	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_bandits_2	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_bandits_3	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_clear_path	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_go_lever_1	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_go_lever_2	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_go_lever_3	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_attention_control	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_start_lower	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_leshiy_reply	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_leshiy_start	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_lever_killed_first	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_lever_killed_1	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_lever_killed_2	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_lever_killed_first	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_lowered	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_sniper_1	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_sniper_2	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_sniper_3	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_spawn_bandits_1	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_spawn_bandits_2	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_bridge_spawn_bandits_3	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_pursuit_camfly_1	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_pursuit_camfly_2	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_pursuit_camfly_3	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_pursuit_camfly_4	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_pursuit_camfly_5	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_pursuit_locate_strelok	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_pursuit_strelok_threat	=	{5, "temporal_icon"},
	characters_voice_scenario_red_forest_red_pursuit_strelok_spich	=	{5, "temporal_icon"},
	characters_voice_human_01_stalker_alife_defence_wait_help_2_pda	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_first_scene_petrenko_talk_1	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_first_scene_scout_talk_1	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_first_scene_objective_talk_1	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_first_scene_objective_talk_2	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_strelok_kill_reminder_1	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_strelok_kill_reminder_2	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_strelok_kill_reminder_3	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_strelok_kill_reminder_4	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_strelok_kill_reminder_5	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_strelok_kill_reminder_6	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_final_scene_after_kill_strelok_1	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_final_scene_after_kill_strelok_2	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_final_scene_after_kill_strelok_3	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_final_scene_after_kill_strelok_4	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_final_scene_after_kill_strelok_5	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_final_scene_after_lost_strelok_1	=	{5, "temporal_icon"},
	characters_voice_scenario_stancia_stc_final_scene_after_lost_strelok_2	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_not_go_to_roof	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_actor_on_roof	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_group_in_angar	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_roof_ready	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_wave1_go	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_wave_naval	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_roof_nores_stalker3	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_roof_nores_stalker4	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_roof_nores_stalker5	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_wave_naval_roof1	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_wave_naval_roof	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_wave_clear_roof	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_squad1_ready	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_squad2_ready	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_building_wave	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_wave_repealed_1	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_wave_repealed_2	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_wave_repealed_3	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_truck_wave	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_alarm_roof	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_freezer_fixed	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_psy_reduced	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_go_red_forest	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_alarm_hangar	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_psy_reduced_reply	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_squad_assemble	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_professr_reply_actor	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_professor_about_switcher	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_levsha_reply_switcher	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_professor_start_operation	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_levsha_clear	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_squad_diary	=	{5, "temporal_icon"},
	characters_voice_scenario_yantar_yan_levsha_check_actor_position_2	=	{5, "temporal_icon"},
}

--id																												=	{color, showtime, [distance, or sender]}
obj_snds =
{
	characters_voice_scenario_agroprom_agr_base_dolg_megafon_1	=	{2, 13.3, 4500},
	characters_voice_scenario_agroprom_agr_base_dolg_megafon_2	=	{2, 9, 4500},
	characters_voice_scenario_agroprom_agr_base_dolg_megafon_3	=	{2, 5.6, 4500},
	characters_voice_scenario_agroprom_agr_base_dolg_megafon_4	=	{2, 8.5, 4500},
	characters_voice_scenario_agroprom_agr_base_dolg_megafon_5	=	{2, 12.4, 4500},
	characters_voice_scenario_agroprom_agr_base_dolg_megafon_6	=	{2, 11.7, 4500},
	characters_voice_scenario_agroprom_agr_base_dolg_megafon_7	=	{2, 5, 4500},
	characters_voice_scenario_darkvalley_val_freedom_dead_squad_1	=	{-1, 3, "val_freedom_comendant_name"},
	characters_voice_scenario_darkvalley_val_freedom_dead_squad_2	=	{-1, 2.1, "val_freedom_comendant_name"},
	characters_voice_scenario_darkvalley_val_freedom_dead_squad_3	=	{-1, 1.8, "val_freedom_comendant_name"},
	characters_voice_scenario_darkvalley_val_freedom_megafon_1	=	{2, 26.5, 4500},
	characters_voice_scenario_darkvalley_val_freedom_megafon_2	=	{2, 14.9, 4500},
	characters_voice_scenario_darkvalley_val_freedom_megafon_3	=	{2, 13.8, 4500},
	characters_voice_scenario_darkvalley_val_freedom_megafon_4	=	{2, 18.2, 4500},
	characters_voice_scenario_darkvalley_val_freedom_megafon_5	=	{2, 11.6, 4500},
	characters_voice_scenario_darkvalley_val_freedom_megafon_6	=	{2, 9.1, 4500},
	characters_voice_scenario_darkvalley_val_freedom_megafon_7	=	{2, 8.5, 4500},
	characters_voice_scenario_darkvalley_val_freedom_megafon_rugan_1	=	{2, 26.6, 4500},
	characters_voice_scenario_darkvalley_val_freedom_megafon_rugan_2	=	{2, 26.4, 4500},
	characters_voice_scenario_darkvalley_val_freedom_megafon_rugan_3	=	{2, 25.4, 4500},
	characters_voice_scenario_escape_megafon_1	=	{2, 10.9, 25000},
	characters_voice_scenario_escape_megafon_2	=	{2, 9.2, 25000},
	characters_voice_scenario_escape_megafon_3	=	{2, 14.8, 25000},
	characters_voice_scenario_escape_megafon_4	=	{2, 31.6, 25000},
	characters_voice_scenario_escape_megafon_alarm_1	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_2	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_3	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_4	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_5	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_6	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_7	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_8	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_9	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_10	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_11	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_12	=	{2, 5, 25000},
	characters_voice_scenario_escape_megafon_alarm_13	=	{2, 5, 25000},
	characters_voice_scenario_escape_esc_mil_target_lost	=	{1, 3.8, 25000},
	characters_voice_scenario_escape_esc_mil_target_detected	=	{1, 3.3, 25000},
	characters_voice_scenario_garbage_gar_robbery_scene_come_here_1	=	{-1, 3.5, "gar_bandit_robbery"},
	characters_voice_scenario_garbage_gar_robbery_scene_come_here_2	=	{-1, 3.5, "gar_bandit_robbery"},
	characters_voice_scenario_garbage_gar_robbery_scene_come_here_3	=	{-1, 3.6, "gar_bandit_robbery"},
	characters_voice_scenario_garbage_gar_robbery_scene_return_1	=	{-1, 3.3, "gar_bandit_robbery"},
	characters_voice_scenario_garbage_gar_robbery_scene_return_2	=	{-1, 2.5, "gar_bandit_robbery"},
	characters_voice_scenario_garbage_gar_robbery_scene_return_3	=	{-1, 2.6, "gar_bandit_robbery"},
	-- characters_voice_scenario_hospital_hospital_gunfire_1	=	{-1, 5, "temporal_icon"},
	-- characters_voice_scenario_hospital_hospital_sniper_1	=	{-1, 5, "temporal_icon"},
	-- characters_voice_scenario_hospital_expl_door	=	{-1, 5, "temporal_icon"},
}

-- p:string
function cc_display_mobsnd(p)
	local cc_id = string.gsub(p, "\\", "_")
	local cc_value = mob_snds[cc_id]
	if cc_value then
		cc_display_subs(cc_id, 1, cc_value[1]) -- only for Sid and Forester
	end
end

-- cc_id:string
function cc_display_npcsnd(cc_id)
	local cc_value = npc_snds[cc_id]
	if cc_value then
		cc_display_subs("cc_" .. cc_id, 1, cc_value[1]) -- only for greetings and farewells
	end
end

-- p:string, obj:userdata
function cc_display_sndpath(p, obj)
	local cc_id = string.gsub(p, "\\", "_")
	local cc_value = actor_snds[cc_id]
	if cc_value then
		cc_send_tip(cc_id, cc_value[1]*1000, cc_value[2]) -- pda message
	else
		cc_value = obj_snds[cc_id]
		if cc_value then
			if cc_value[1] == -1 then
				cc_send_tip(cc_id, cc_value[2]*1000, cc_value[3]) -- pda message
			elseif cc_value[1] >= 1 and obj ~= nil then
				local dist = obj:position():distance_to_sqr(db.actor:position())
				if dist <= cc_value[3] then
					cc_display_subs(cc_id, cc_value[1], cc_value[2]) -- megafon and soldier
				end
			end
		end
	end
end

-- cc_id:string, color:number, showtime:number
function cc_display_subs(cc_id, color, showtime)
	if color == nil or showtime == nil then return end
	if db.actor:is_talking() then return end
	if db.cc_npc == true then
		local time_now = time_global() / 1000
		local time_ccend = time_now + showtime

		local tmpl = "closecaption_" .. color
		local hud = get_hud()
		hud:AddCustomStatic(tmpl, true)
		hud:GetCustomStatic(tmpl):wnd():SetTextST(game.translate_string(cc_id))
		hud:GetCustomStatic(tmpl).m_endTime = time_ccend
	elseif db.cc_npc == nil then
		read_cc_ini()
		if db.cc_npc ~= nil then
			cc_display_subs(cc_id, color, showtime)
		end
	end
end

-- news_id:string, showtime:number, sender:string
function cc_send_tip(news_id, showtime, sender)
	if showtime == nil or sender == nil then return end
	if db.cc_npc == true then

		local texture = tips_icons[sender]
		local news_caption = game.translate_string("st_tip") .. ":"
		local news_text = game.translate_string(news_id)

		db.actor:give_game_news(news_caption, news_text, texture, 0, showtime, 1)
	elseif db.cc_npc == nil then
		read_cc_ini()
		if db.cc_npc ~= nil then
			cc_send_tip(news_id, showtime, sender)
		end
	end
end

function read_cc_ini()
	-------- read values from the closecaption.ltx file
	-------- commented lines used as reference if they need to be used in the future
	local cc = "closecaption"
	-- local p_igm, cc_igm, cc_npc, cc_icc, cc_nip = true, false, false, false, false
	local cc_npc = false
	cc_npc = load_variable("cc_npc", 0)
	if cc_npc == 0 then
		local ini = ini_file("misc\\closecaption.ltx")
		if ini:section_exist(cc) then
			--[[
			if ini:line_exist(cc, "play_igm") then
       				p_igm = ini:r_bool(cc, "play_igm")
			end
			 ]]
			--[[
 			if ini:line_exist(cc, "cc_ingame_video") then
				cc_igm = ini:r_bool(cc, "cc_ingame_video")
			end
			 ]]
			if ini:line_exist(cc, "cc_ingame_npc") then
				cc_npc = ini:r_bool(cc, "cc_ingame_npc")
			end
			--[[
 			if ini:line_exist(cc, "cc_ingame_cc") then
				cc_icc = ini:r_bool(cc, "cc_ingame_cc")
			end
			 ]]
			--[[
			if ini:line_exist(cc, "cc_add_new_info") then
				cc_nip = ini:r_bool(cc, "cc_add_new_info")
			end
			 ]]
			--[[
			if ini:line_exist(cc, "cc_video_player") then
				cc_vpl = ini:r_bool(cc, "cc_video_player")
			end
			 ]]
		end
		-- db.p_igm = p_igm
		-- db.cc_igm = cc_igm
		db.cc_npc = cc_npc
		-- db.cc_icc = cc_icc
		-- db.cc_nip = cc_nip
		-- save_variable("cc_nip", cc_nip)
		-- save_variable("cc_icc", cc_icc)
		save_variable("cc_npc", cc_npc)
		-- save_variable("cc_igm", cc_igm)
		-- save_variable("p_igm", p_igm)
	else
		-- cc_nip = load_variable("cc_nip", cc_nip)
		-- cc_icc = load_variable("cc_icc", cc_icc)
		-- cc_igm = load_variable("cc_igm", cc_igm)
		-- p_igm = load_variable("p_igm", p_igm)
		-- db.p_igm = p_igm
		-- db.cc_igm = cc_igm
		db.cc_npc = cc_npc
		-- db.cc_icc = cc_icc
		-- db.cc_nip = cc_nip
	end
end

-- code portions from the excellent AMK mod --
function save_variable(variable_name, value)
  xr_logic.pstor_store(db.actor, variable_name, value)
end

function load_variable(variable_name, value_if_not_found)
  return xr_logic.pstor_retrieve(db.actor, variable_name, value_if_not_found)
end

function del_variable(variable_name)
  if db.storage[db.actor:id()].pstor[variable_name] then
    db.storage[db.actor:id()].pstor[variable_name] = nil
  end
end
